//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpansionDownloader.Sample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int MainPlay = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int MyVideo = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int PatchPlay = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int appIcon = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int approveCellular = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int buttonRow = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int cancelButton = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int description = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int downloaderDashboard = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int pauseButton = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int paused_text = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int progressAsFraction = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int progressAsPercentage = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int progressAverageSpeed = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int progressBar = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int progressTimeRemaining = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int progress_bar = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int progress_bar_frame = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int progress_text = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int resumeOverCellular = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int statusText = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int textPausedParagraph1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textPausedParagraph2 = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int time_remaining = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int title = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int wifiSettingsButton = 2131099662;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int status_bar_ongoing_event_progress_bar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int video_player = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int text_button_cancel = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int text_button_cancel_verify = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int text_button_pause = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text_button_resume = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int text_button_resume_cellular = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int text_button_wifi_settings = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int text_paused_cellular = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text_paused_cellular_2 = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int text_validation_complete = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int text_validation_failed = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int text_verifying_download = 2130968581;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050004
			public const int ButtonBackground = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int NotificationText = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int NotificationTextShadow = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NotificationTitle = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int VideoFullScreen = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
