//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperSimpleSpansions
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int approve = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btnCancel = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btnPause = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int btnResumeCell = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnWifi = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int dashboard = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lblProgress = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int lblStatus = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int prgProgress = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int progressAsFraction = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int text_button_cancel = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int text_button_cancel_verify = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int text_button_pause = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text_button_resume = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int text_button_resume_cellular = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int text_button_wifi_settings = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int text_paused_cellular = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text_paused_cellular_2 = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int text_validation_complete = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int text_validation_failed = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int text_verifying_download = 2130968581;
			
			private String()
			{
			}
		}
	}
}
