//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseVerificationLibrary.Tests
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int RunTests = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int check_license_button = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_text = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int allow = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int application_error = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int buy_button = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int check_license = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int checking_license = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dont_allow = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int quit_button = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int retry_button = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int unlicensed_dialog_body = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int unlicensed_dialog_retry_body = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int unlicensed_dialog_title = 2130968582;
			
			private String()
			{
			}
		}
	}
}
